version: '3.8'

services:
  fastapi-app:
    image: your-dockerhub-username/my-fastapi-app:latest  # Replace with your actual image name
    container_name: fastapi-container
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always
